Actualys\Bundle\DrupalCommerceConnectorBundle\Entity\ProductExport:
    type: entity
    table: pim_drupal_product_export
    indexes:
        searchcode_idx:
            columns:
                - id
    repositoryClass: Actualys\Bundle\DrupalCommerceConnectorBundle\Entity\Repository\ProductExportRepository
    uniqueConstraints:
        searchunique_idx:
            columns:
                - id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        date:
            type: datetime
    manyToOne:
        product:
            targetEntity: Pim\Component\Catalog\Model\ProductInterface
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        jobInstance:
            targetEntity: Akeneo\Component\Batch\Model\JobInstance
            joinColumns:
                job_instance_id:
                    referencedColumnName: id
                    onDelete: CASCADE
